algoritmo "LerNomeEndereco"

// Variáveis
var
   nome, endereco: caractere

// Início
inicio
   // Entrada e leitura de dados
   Escreva("Informe seu nome: ")
   Leia(nome)
   Escreva("Informe seu endereço: ")
   Leia(endereco)

   // Saída de dados
   Escreval("Seu nome: ", nome)
   Escreval("Seu endereço: ", endereco)

// Fim da execução
fimalgoritmo

// Faça um algoritmo que irá ler o nome e o endereço
// de uma pessoa, consequentemente mostrando os
// dados inseridos ao final.