algoritmo "SomaDoisValores"

// Variáveis
var
   x, y, soma: real

// Início
inicio
   // Entrada e leitura de dados
   Escreva("Informe o valor de X: ")
   Leia(x)
   Escreva("Informe o valor de Y: ")
   Leia(y)

   // Processamento
   soma <- x + y

   // Saída de dados
   Escreval("A soma entre X e Y é ", soma)

// Fim da execução
fimalgoritmo

// Desenvolva um algoritmo para calcular
// x + y. Os valores de x e y serão fornecidos
// pelo usuário do programa.