algoritmo "LerNomeIdade"

// Variáveis
var
   nome: caractere
   idade: inteiro

// Início
inicio
   // Entrada e leitura de dados
   Escreva("Informe seu nome: ")
   Leia(nome)
   Escreva("Informe sua idade: ")
   Leia(idade)

   // Saída de dados
   Escreval("Seu nome é: ", nome)
   Escreval("Sua idade é: ", idade)

// Fim da execução
fimalgoritmo

// Faça um algoritmo que permita ao usuário
// informar  o nome e idade e como resultado
// será mostrado os dados informados pelo usuário.