algoritmo "MetrosParaCentimetros"

// Variáveis
var
   metros, centimetros: real

// Início
inicio
   // Entrada e leitura de dados
   Escreva("Informe um valor em metros: ")
   Leia(metros)

   // Processamento
   centimetros <- metros * 100

   // Saída de dados
   Escreval(metros, " metros = ", centimetros, " centímetros")

// Fim da execução
fimalgoritmo

// Crie um algoritmo que leia um valor em metros e
// converta para centímetros.