algoritmo "CompararNumeroVinte"

// Variáveis
var
   n: real

// Início
inicio
   // Entrada e leitura de dados
   Escreva("Informe um valor: ")
   Leia(n)

   // Lógica condicional para saída de dados
   se (n > 20) entao
      Escreval(n, " é maior que 20")
   senao
      Escreval(n, " é menor que 20")
   fimse

// Fim da execução
fimalgoritmo

// Escreva um algoritmo em PORTUGOL
// que leia um número e o imprima se ele
// é maior ou menor que 20.