algoritmo "NumerosImparesVinte"

// Variáveis
var
   n: inteiro

// Início
inicio
   // Loop para processamento
   para n <- 0 ate 20 passo 1 faca
      // Lógica condicional para saída de dados
      se (n mod 2 <> 0) entao
         Escreval(n)
      fimse
   fimpara

// Fim da execução
fimalgoritmo

// Elaborar um algoritmo que apresente todos
// os valores numéricos inteiros ímpares
// situados na faixa de 0 a 20.